// Generated by Rivet. Do not edit by hand.
import Foundation
import RivetRuntime

public enum RivetGeneratedError: Error { case typeMismatch(String); case unknownEvent(String) }
public enum RivetGeneratedConfig { public static let moduleName = "backend"; public static let entryName = "start" }

private func encode_String(_ v: String) -> RivetValue { .string(v) }
private func encode__List_String_(_ v: [String]) -> RivetValue { .list(v.map(encode_String)) }
private func encode__List_List_String_(_ v: [[String]]) -> RivetValue { .list(v.map(encode__List_String_)) }
private func encode_Bool(_ v: Bool) -> RivetValue { .bool(v) }
private func encode_Int64(_ v: Int64) -> RivetValue { .int64(v) }
private func encode_Void(_ v: Void) -> RivetValue { .null }

private func decode_String(_ v: RivetValue) throws -> String { guard case .string(let x) = v else { throw RivetGeneratedError.typeMismatch("String") }; return x }
private func decode__List_String_(_ v: RivetValue) throws -> [String] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List String)") }; return try xs.map(decode_String) }
private func decode__List_List_String_(_ v: RivetValue) throws -> [[String]] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List (List String))") }; return try xs.map(decode__List_String_) }
private func decode_Bool(_ v: RivetValue) throws -> Bool { guard case .bool(let x) = v else { throw RivetGeneratedError.typeMismatch("Bool") }; return x }
private func decode_Int64(_ v: RivetValue) throws -> Int64 { guard case .int64(let x) = v else { throw RivetGeneratedError.typeMismatch("Int64") }; return x }
private func decode_Void(_ v: RivetValue) throws -> Void { guard case .null = v else { throw RivetGeneratedError.typeMismatch("Void") } }

public enum RivetEvent: Sendable {
    case episodes_changed(String)
    case job_progress([String])
    case notify(String)
    case open_url(String)
    case update_available(String)

    public static func decode(name: String, value: RivetValue) throws -> RivetEvent {
        switch name {
        case "episodes-changed": return .episodes_changed(try decode_String(value))
        case "job-progress": return .job_progress(try decode__List_String_(value))
        case "notify": return .notify(try decode_String(value))
        case "open-url": return .open_url(try decode_String(value))
        case "update-available": return .update_available(try decode_String(value))
        default: throw RivetGeneratedError.unknownEvent(name)
        }
    }
}

public struct RivetAPI: Sendable {
    public let client: RivetClient
    public init(client: RivetClient) { self.client = client }

    public func catalog_list() async throws -> [[String]] {
        let result = try await client.call("catalog-list", arguments: [])
        return try decode__List_List_String_(result)
    }
    public func catalog_search(query: String) async throws -> [[String]] {
        let result = try await client.call("catalog-search", arguments: [encode_String(query)])
        return try decode__List_List_String_(result)
    }
    public func episode_download(id: String) async throws -> String {
        let result = try await client.call("episode-download", arguments: [encode_String(id)])
        return try decode_String(result)
    }
    public func episode_list(feed_id: String) async throws -> [[String]] {
        let result = try await client.call("episode-list", arguments: [encode_String(feed_id)])
        return try decode__List_List_String_(result)
    }
    public func episode_remove_audio(id: String) async throws -> Bool {
        let result = try await client.call("episode-remove-audio", arguments: [encode_String(id)])
        return try decode_Bool(result)
    }
    public func episode_summarize(id: String) async throws -> String {
        let result = try await client.call("episode-summarize", arguments: [encode_String(id)])
        return try decode_String(result)
    }
    public func episode_summary(id: String) async throws -> String {
        let result = try await client.call("episode-summary", arguments: [encode_String(id)])
        return try decode_String(result)
    }
    public func episode_transcribe(id: String) async throws -> String {
        let result = try await client.call("episode-transcribe", arguments: [encode_String(id)])
        return try decode_String(result)
    }
    public func episode_transcript(id: String) async throws -> [[String]] {
        let result = try await client.call("episode-transcript", arguments: [encode_String(id)])
        return try decode__List_List_String_(result)
    }
    public func episode_translate(id: String) async throws -> String {
        let result = try await client.call("episode-translate", arguments: [encode_String(id)])
        return try decode_String(result)
    }
    public func feed_add(url: String) async throws -> String {
        let result = try await client.call("feed-add", arguments: [encode_String(url)])
        return try decode_String(result)
    }
    public func feed_list() async throws -> [[String]] {
        let result = try await client.call("feed-list", arguments: [])
        return try decode__List_List_String_(result)
    }
    public func feed_refresh(id: String) async throws -> Int64 {
        let result = try await client.call("feed-refresh", arguments: [encode_String(id)])
        return try decode_Int64(result)
    }
    public func feed_refresh_all() async throws -> Int64 {
        let result = try await client.call("feed-refresh-all", arguments: [])
        return try decode_Int64(result)
    }
    public func feed_remove(id: String) async throws -> Bool {
        let result = try await client.call("feed-remove", arguments: [encode_String(id)])
        return try decode_Bool(result)
    }
    public func health() async throws -> String {
        let result = try await client.call("health", arguments: [])
        return try decode_String(result)
    }
    public func job_status(job_id: String) async throws -> String {
        let result = try await client.call("job-status", arguments: [encode_String(job_id)])
        return try decode_String(result)
    }
    public func open_releases() async throws -> Void {
        let result = try await client.call("open-releases", arguments: [])
        return try decode_Void(result)
    }
    public func position_save(id: String, seconds: String, done: String) async throws -> Bool {
        let result = try await client.call("position-save", arguments: [encode_String(id), encode_String(seconds), encode_String(done)])
        return try decode_Bool(result)
    }
    public func settings_list() async throws -> [[String]] {
        let result = try await client.call("settings-list", arguments: [])
        return try decode__List_List_String_(result)
    }
    public func settings_set(key: String, value: String) async throws -> Bool {
        let result = try await client.call("settings-set", arguments: [encode_String(key), encode_String(value)])
        return try decode_Bool(result)
    }
    public func update_check() async throws -> String {
        let result = try await client.call("update-check", arguments: [])
        return try decode_String(result)
    }

    // Shared state
    public func getVersion() async throws -> String {
        let result = try await client.getState("version")
        return try decode_String(result)
    }
    @discardableResult
    public func setVersion(_ value: String) async throws -> String {
        let result = try await client.setState("version", value: encode_String(value))
        return try decode_String(result)
    }
}
